# html lang
language: zh-Hans

# main menu navigation
menu:
  home: /
  archives: /archives
  tags: /tags
  categories: /categories
  search: /search
  about: /about
  # rss: /atom.xml

# stylesheets loaded in the <head>
stylesheets:
# - /css/main.css

scripts:
# - /js/main.js

hljs_style: 'monokai-sublime' # 'atom-one-dark'

# postItem 文章块
index_post:
  show_excerpt: true # 显示摘要 0
  # maxRows: 2 # 摘要最大展示行数
  show_tags: true # 显示tags
  show_date: true # 显示时间
  word_count: true # 设置文章字数统计为 true.
  min2read: true # 阅读时长.

# 文章详情
postInfo:
  showDate: true
  showTags: true
  wordCount: true # 设置文章字数统计为 true.
  min2read: true # 阅读时长.
  readCount: true # 阅读次数.
  update: false

totalCount: true # 设置站点文章总字数统计为 true.
# admire 赞赏

admireMsg: 觉得写的不错，请我喝杯奶茶呗~
# aliQRcode: https://i.loli.net/2019/11/15/FpoMI3UCqyKxnb8.jpg
# wxQRcode: https://i.loli.net/2019/11/15/FpoMI3UCqyKxnb8.jpg

#footer
index_page: http://lion1ou.win
# juejin: http://lion1ou.win
# zhihu: http://lion1ou.win
# weibo: http://lion1ou.win
github: https://github.com/lion1ou
